# -*- coding: utf-8 -*-
PATTERNS = {
    "pattern-a": {
        "concept": "信頼の実務型",
        "brand_en": "kaigo.",
        "brand_display": "kaigo.",  # ヘッダーに表示するブランド名
        "font_link": "https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;500;700;900&family=IBM+Plex+Mono:wght@500;600&display=swap",
        "font_body": '"Zen Kaku Gothic New","Hiragino Sans",sans-serif',
        "font_head": '"Zen Kaku Gothic New",sans-serif',
        "head_weight": 900,
        "tokens": {
            "bg": "#FFFFFF", "surface": "#FFFFFF", "surface-alt": "#F1F4F7",
            "ink": "#1A2733", "ink-soft": "#5C6B78",
            "line": "#E2E8ED", "line-strong": "#1A2733",
            "accent": "#1E4E7A", "accent-strong": "#153A5C", "accent-tint": "#E7EEF4", "accent-ink": "#FFFFFF",
            "warm": "#1E4E7A", "warm-strong": "#153A5C", "warm-ink": "#FFFFFF",
            "badge-bg": "#E7EEF4", "badge-ink": "#1E4E7A",
            "shadow": "0 18px 40px -24px rgba(26,39,51,0.28)",
            "radius-s": "6px", "radius-m": "12px", "radius-l": "16px",
        },
        "hero": "photo",          # フルブリード写真タイプ
        "testimonial": False,
        "hero_photo": "hero-main.jpg",
    },
    "pattern-b": {
        "concept": "あたたかい安心型",
        "brand_en": "kaigo.",
        "brand_display": "かいごしごと",
        "font_link": "https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@500;700;900&family=Zen+Kaku+Gothic+New:wght@400;500;700&family=IBM+Plex+Mono:wght@500;600&display=swap",
        "font_body": '"Zen Kaku Gothic New","Hiragino Sans",sans-serif',
        "font_head": '"Zen Maru Gothic",sans-serif',
        "head_weight": 900,
        "tokens": {
            "bg": "#FFF9F2", "surface": "#FFFFFF", "surface-alt": "#FBEEDF",
            "ink": "#2B2620", "ink-soft": "#7A6E5E",
            "line": "#F0E0CC", "line-strong": "#E0C29B",
            "accent": "#7A9D54", "accent-strong": "#5E7D3D", "accent-tint": "#EEF3E4", "accent-ink": "#FFFFFF",
            "warm": "#C1592E", "warm-strong": "#9C441F", "warm-ink": "#FFFFFF",
            "badge-bg": "#EEF3E4", "badge-ink": "#5E7D3D",
            "shadow": "0 20px 40px -22px rgba(150,90,40,0.28)",
            "radius-s": "10px", "radius-m": "16px", "radius-l": "22px",
        },
        "hero": "grid",            # 2カラム＋チェックリスト＋フロートバッジ
        "testimonial": True,
        "hero_photo": "hero-main.jpg",
    },
    "pattern-c": {
        "concept": "現場のリアル型",
        "brand_en": "kaigo.",
        "brand_display": "かいごしごと",
        "font_link": "https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@500;700;800&family=Zen+Kaku+Gothic+New:wght@400;500;700&family=IBM+Plex+Mono:wght@500;600&display=swap",
        "font_body": '"Zen Kaku Gothic New","Hiragino Sans",sans-serif',
        "font_head": '"Shippori Mincho",serif',
        "head_weight": 800,
        "tokens": {
            "bg": "#FAF7F0", "surface": "#FFFFFF", "surface-alt": "#F1ECDD",
            "ink": "#2A2A24", "ink-soft": "#6B6B5E",
            "line": "#E8E1CE", "line-strong": "#2A2A24",
            "accent": "#2B3A55", "accent-strong": "#1C2740", "accent-tint": "#E8EAEF", "accent-ink": "#FFFFFF",
            "warm": "#D9A441", "warm-strong": "#B3852B", "warm-ink": "#2A1B05",
            "badge-bg": "#E8EAEF", "badge-ink": "#2B3A55",
            "shadow": "0 18px 40px -24px rgba(42,42,36,0.30)",
            "radius-s": "4px", "radius-m": "10px", "radius-l": "14px",
        },
        "hero": "photo",
        "testimonial": True,
        "hero_photo": "hero-main.jpg",
    },
}
